import { Router, type IRouter } from "express";
import healthRouter from "./health";
import productsRouter from "./products";
import cartRouter from "./cart";
import ordersRouter from "./orders";
import reviewsRouter from "./reviews";
import wishlistRouter from "./wishlist";
import couponsRouter from "./coupons";
import usersRouter from "./users";
import adminRouter from "./admin";
import categoriesRouter from "./categories";
import monthlyRecordsRouter from "./monthlyRecords";
import abandonedCartRouter from "./abandonedCart";
import referralsRouter from "./referrals";
import loyaltyRouter from "./loyalty";
import stockAlertsRouter from "./stockAlerts";
import newsletterRouter from "./newsletter";
import auditLogsRouter from "./auditLogs";
import productQARouter from "./productQA";
import sitemapRouter from "./sitemap";
import exportRouter from "./export";
import returnsRouter from "./returns";
import variantsRouter from "./variants";
import bulkImportRouter from "./bulkImport";
import affiliatesRouter from "./affiliates";
import analyticsRouter from "./analytics";
import pushRouter from "./push";
import skinProfileRouter from "./skinProfile";
import subscriptionsRouter from "./subscriptions";
import giftCardsRouter from "./giftCards";
import emailPreferencesRouter from "./emailPreferences";
import searchRouter from "./search";
import flashSalesRouter from "./flashSales";
import blogPostsRouter from "./blogPosts";

const router: IRouter = Router();

router.use(healthRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(cartRouter);
router.use(ordersRouter);
router.use(reviewsRouter);
router.use(wishlistRouter);
router.use(couponsRouter);
router.use(usersRouter);
router.use(adminRouter);
router.use(monthlyRecordsRouter);
router.use(abandonedCartRouter);
router.use(referralsRouter);
router.use(loyaltyRouter);
router.use(stockAlertsRouter);
router.use(newsletterRouter);
router.use(auditLogsRouter);
router.use(productQARouter);
router.use(sitemapRouter);
router.use(exportRouter);
router.use(returnsRouter);
router.use(variantsRouter);
router.use(bulkImportRouter);
router.use(affiliatesRouter);
router.use(analyticsRouter);
router.use(pushRouter);
router.use(skinProfileRouter);
router.use(subscriptionsRouter);
router.use(giftCardsRouter);
router.use(emailPreferencesRouter);
router.use(searchRouter);
router.use(flashSalesRouter);
router.use(blogPostsRouter);

export default router;
